### **Librerías**

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from plotly.subplots import make_subplots

### **Parámetros**

In [2]:
os.chdir("/Users/juanchacon/Library/Mobile Documents/com~apple~CloudDocs/GitHub/bot_futuros")

SILVER_DATA_PATH = os.getcwd() + "/data/silver/"

dict_files = {
    "futuros": "precios_FUTUROS.csv",
    "precios": "datos_PRECIOS.csv",
    "precios_ponderados": "datos_PRECIOS_PONDERADOS.csv",
    "demanda": "datos_DEMANDA.csv",
    "demanda_comprador": "datos_DEMANDA_COMPRADOR.csv",
    "aportes_hidricos": "datos_APORTES_HIDRICOS.csv",
    "niveles_embalse": "datos_NIVELES_EMBALSE.csv",
    "generacion": "datos_GENERACION_REAL.csv",
    "disponibilidad": "datos_DISPONIBILIDAD_REAL.csv",
}

start_date = "2024-01-01"
end_date = "2026-01-31"

### **Análisis Univariado**

#### **Futuros**

In [3]:
# Carga de datos
df_futuros = pd.read_csv(SILVER_DATA_PATH + dict_files["futuros"], parse_dates=["Fecha", "FechaVencimientoContrato"])

# Filtrar por rango de fechas
mask = (df_futuros["Fecha"] >= start_date) & (df_futuros["Fecha"] <= end_date)
df_futuros = df_futuros.loc[mask]

# Forma del DataFrame
print(f"El DataFrame de futuros tiene {df_futuros.shape[0]} filas y {df_futuros.shape[1]} columnas.")

# Revisar las primeras filas del DataFrame
display(df_futuros.head())

El DataFrame de futuros tiene 73296 filas y 7 columnas.

  Nemotecnico Tipo    Mes   Año      Fecha FechaVencimientoContrato  Precio
0     ELMF26F  ELM  Enero  2026 2026-01-02               2026-01-31  390.05
1     ELMF26F  ELM  Enero  2026 2026-01-05               2026-01-31  386.97
2     ELMF26F  ELM  Enero  2026 2026-01-06               2026-01-31  383.41
3     ELMF26F  ELM  Enero  2026 2026-01-07               2026-01-31  379.84
4     ELMF26F  ELM  Enero  2026 2026-01-08               2026-01-31  374.07

In [4]:
# Revisar la estructura del DataFrame
df_futuros.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73296 entries, 0 to 74735
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Nemotecnico               73296 non-null  object
 1   Tipo                      73296 non-null  object
 2   Mes                       73296 non-null  object
 3   Año                       73296 non-null  int64
 4   Fecha                     73296 non-null  datetime64[ns]
 5   FechaVencimientoContrato  73296 non-null  datetime64[ns]
 6   Precio                    73296 non-null  float64
dtypes: datetime64[ns](2), float64(1), int64(1), object(3)
memory usage: 4.5+ MB

In [5]:
# Revisar si hay valores nulos
print("\nValores nulos por columna:")
df_futuros.isnull().sum()

Valores nulos por columna:

Nemotecnico                 0
Tipo                        0
Mes                         0
Año                         0
Fecha                       0
FechaVencimientoContrato    0
Precio                      0
dtype: int64

In [6]:
# Estadísticas descriptivas, histograma y violin plot para cada tipo de contrato
cols_analyze = ["Fecha", "FechaVencimientoContrato", "Precio"]
for tipo in df_futuros["Tipo"].unique():
    print(f"\nEstadísticas para contratos de tipo: {tipo}")
    temp_df = df_futuros[df_futuros["Tipo"] == tipo]
    display(temp_df[cols_analyze].describe())

    # 1. Crear la estructura de la figura (1 fila, 2 columnas)
    datos_filtrados = temp_df["Precio"] # Asegurarse de no incluir NaN en los gráficos
    fig = make_subplots(
        rows=1, cols=1,
        subplot_titles=(f"Histograma de Precios - {tipo}")
    )

    # 2. Agregar el Histograma (Columna 1)
    # Nota: Plotly puro no trae la curva KDE automática como Seaborn, 
    # pero el histograma interactivo es muy potente.
    fig.add_trace(
        go.Histogram(
            x=datos_filtrados,
            name="Histograma",
            marker_color='#1f77b4',  # Un azul estándar
            opacity=0.75
        ),
        row=1, col=1
    )

    # 3. Actualizar el diseño general (Layout)
    fig.update_layout(
        title_text=f"Análisis de Distribución - {tipo}",
        showlegend=False,           # Ocultamos la leyenda para limpiar la vista
        template="plotly_white",    # Fondo blanco estilo Seaborn
        height=500,                 # Altura similar a figsize=(10,4)
        width=500
    )

    # Etiquetas de los ejes
    fig.update_xaxes(title_text="Precio (COP/kWh)", row=1, col=1)
    fig.update_yaxes(title_text="Frecuencia", row=1, col=1)

    fig.show()

Estadísticas para contratos de tipo: ELM

,Fecha,FechaVencimientoContrato,Precio
count,36648,36648,36648.000000
mean,2025-01-14 02:12:57.996070656,2028-01-13 22:41:43.732809472,388.084391
min,2024-01-02 00:00:00,2024-01-31 00:00:00,110.000000
25%,2024-07-10 00:00:00,2026-06-30 00:00:00,360.000000
50%,2025-01-16 00:00:00,2027-12-31 00:00:00,377.315000
75%,2025-07-23 00:00:00,2029-06-30 00:00:00,409.342500
max,2026-01-30 00:00:00,2031-12-31 00:00:00,941.370000
std,NaN,NaN,56.568539

Estadísticas para contratos de tipo: MTB

,Fecha,FechaVencimientoContrato,Precio
count,12216,12216,12216.000000
mean,2025-01-14 02:12:57.996070656,2026-01-13 11:00:42.436149248,343.560368
min,2024-01-02 00:00:00,2024-01-31 00:00:00,111.930000
25%,2024-07-10 00:00:00,2025-05-31 00:00:00,310.002500
50%,2025-01-16 00:00:00,2025-12-31 00:00:00,336.370000
75%,2025-07-23 00:00:00,2026-08-31 00:00:00,367.780000
max,2026-01-30 00:00:00,2027-12-31 00:00:00,932.490000
std,NaN,NaN,80.914989

Estadísticas para contratos de tipo: DTB

,Fecha,FechaVencimientoContrato,Precio
count,12216,12216,12216.000000
mean,2025-01-14 02:12:57.996070656,2026-01-13 11:00:42.436149248,404.826023
min,2024-01-02 00:00:00,2024-01-31 00:00:00,119.150000
25%,2024-07-10 00:00:00,2025-05-31 00:00:00,367.640000
50%,2025-01-16 00:00:00,2025-12-31 00:00:00,398.080000
75%,2025-07-23 00:00:00,2026-08-31 00:00:00,436.710000
max,2026-01-30 00:00:00,2027-12-31 00:00:00,932.490000
std,NaN,NaN,89.540748

Estadísticas para contratos de tipo: NTB

,Fecha,FechaVencimientoContrato,Precio
count,12216,12216,12216.000000
mean,2025-01-14 02:12:57.996070656,2026-01-13 11:00:42.436149248,416.914098
min,2024-01-02 00:00:00,2024-01-31 00:00:00,137.660000
25%,2024-07-10 00:00:00,2025-05-31 00:00:00,376.600000
50%,2025-01-16 00:00:00,2025-12-31 00:00:00,409.490000
75%,2025-07-23 00:00:00,2026-08-31 00:00:00,445.550000
max,2026-01-30 00:00:00,2027-12-31 00:00:00,935.040000
std,NaN,NaN,91.561207

In [7]:
# Violin plot para cada tipo de contrato en un sólo gráfico
colors_dict = {
    "ELM": '#1f77b4',  # Azul
    "MTB": '#ff7f0e',  # Naranja
    "DTB": '#2ca02c',  # Verde
    "NTB": '#d62728',  # Rojo
}
fig = go.Figure()
for tipo in df_futuros["Tipo"].unique():
    datos_filtrados = df_futuros[df_futuros["Tipo"] == tipo]["Precio"].dropna()
    fig.add_trace(
        go.Violin(
            y=datos_filtrados,
            name=tipo,
            box_visible=True,  # Mostrar caja dentro del violín
            meanline_visible=True,  # Mostrar línea de la media
            line_color='black',  # Color de la línea del violín
            fillcolor=colors_dict[tipo],  # Color de relleno según tipo
            opacity=0.75
        )
    )
fig.update_layout(
    title_text="Violin Plot de Precios por Tipo de Contrato",
    template="plotly_white",
    height=500,
    width=1000,
    yaxis_title="Precio (COP/kWh)"
)

fig.show()

#### **Precios**

In [8]:
# Carga de datos de precios
df_precios = pd.read_csv(SILVER_DATA_PATH + dict_files["precios"], parse_dates=["Fecha"])
df_precios_pond = pd.read_csv(SILVER_DATA_PATH + dict_files["precios_ponderados"], parse_dates=["Fecha"])

df_precios = pd.merge(df_precios, df_precios_pond, on="Fecha")

# Filtrar por rango de fechas
mask = (df_precios["Fecha"] >= start_date) & (df_precios["Fecha"] <= end_date)
df_precios = df_precios.loc[mask]

# Forma del DataFrame
print(f"El DataFrame de precios tiene {df_precios.shape[0]} filas y {df_precios.shape[1]} columnas.")

# Revisar las primeras filas del DataFrame
display(df_precios.head())

El DataFrame de precios tiene 762 filas y 6 columnas.

,Fecha,Precio_COP/kWh_0-7,Precio_COP/kWh_7-17,Precio_COP/kWh_17-23,Precio_COP/kWh_Dia,Precio_Ponderado_COP/kWh
0,2024-01-01,224.3291,156.024933,293.798029,218.976808,225.6200
1,2024-01-02,345.0400,418.977500,444.491786,401.773333,401.7086
2,2024-01-03,428.7116,454.044933,507.997314,461.336600,464.5904
3,2024-01-04,500.9616,576.267156,594.273171,556.417058,562.1373
4,2024-01-05,608.7136,618.149822,644.140171,622.584933,624.2250

In [9]:
# Revisar la estructura del DataFrame
df_precios.info()

<class 'pandas.core.frame.DataFrame'>
Index: 762 entries, 0 to 761
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Fecha                     762 non-null    datetime64[ns]
 1   Precio_COP/kWh_0-7        762 non-null    float64
 2   Precio_COP/kWh_7-17       762 non-null    float64
 3   Precio_COP/kWh_17-23      762 non-null    float64
 4   Precio_COP/kWh_Dia        762 non-null    float64
 5   Precio_Ponderado_COP/kWh  762 non-null    float64
dtypes: datetime64[ns](1), float64(5)
memory usage: 41.7 KB

In [10]:
# Revisar si hay valores nulos
print("\nValores nulos por columna:")
df_precios.isnull().sum()

Valores nulos por columna:

Fecha                       0
Precio_COP/kWh_0-7          0
Precio_COP/kWh_7-17         0
Precio_COP/kWh_17-23        0
Precio_COP/kWh_Dia          0
Precio_Ponderado_COP/kWh    0
dtype: int64

In [11]:
# Estadísticas descriptivas, histograma y violin plot
print(f"\nEstadísticas para los datos de precios spot:")
display(df_precios.describe())

cols_precios = [x for x in df_precios.columns if x not in ["Fecha"]]

for tipo in cols_precios:
    # 1. Crear la estructura de la figura (1 fila, 2 columnas)
    datos_filtrados = df_precios[tipo].dropna() # Asegurarse de no incluir NaN en los gráficos
    fig = make_subplots(
        rows=1, cols=1,
        subplot_titles=(f"Histograma de Precios - {tipo}")
    )

    # 2. Agregar el Histograma (Columna 1)
    # Nota: Plotly puro no trae la curva KDE automática como Seaborn, 
    # pero el histograma interactivo es muy potente.
    fig.add_trace(
        go.Histogram(
            x=datos_filtrados,
            name="Histograma",
            marker_color='#1f77b4',  # Un azul estándar
            opacity=0.75
        ),
        row=1, col=1
    )

    # 5. Actualizar el diseño general (Layout)
    fig.update_layout(
        title_text=f"Análisis de Distribución - {tipo}",
        showlegend=False,           # Ocultamos la leyenda para limpiar la vista
        template="plotly_white",    # Fondo blanco estilo Seaborn
        height=500,                 # Altura similar a figsize=(10,4)
        width=500
    )

    # Etiquetas de los ejes
    fig.update_xaxes(title_text="Precio (COP/kWh)", row=1, col=1)
    fig.update_yaxes(title_text="Frecuencia", row=1, col=1)

    fig.show()

Estadísticas para los datos de precios spot:

,Fecha,Precio_COP/kWh_0-7,Precio_COP/kWh_7-17,Precio_COP/kWh_17-23,Precio_COP/kWh_Dia,Precio_Ponderado_COP/kWh
count,762,762.000000,762.000000,762.000000,762.000000,762.000000
mean,2025-01-15 12:00:00,401.050216,453.533902,543.227299,462.199914,460.977960
min,2024-01-01 00:00:00,90.632350,93.930878,99.813443,95.210350,102.889300
25%,2024-07-09 06:00:00,119.896744,154.287742,267.706043,183.667029,191.536750
50%,2025-01-15 12:00:00,243.823450,291.753706,404.110943,305.408900,310.084150
75%,2025-07-24 18:00:00,568.299625,621.478308,687.355925,620.277294,613.756350
max,2026-01-31 00:00:00,7235.163800,7235.163800,7235.163800,7235.163800,7235.166800
std,NaN,436.755725,470.799975,491.578082,459.625708,457.940183

In [12]:
# Violin plot para cada tipo de contrato en un sólo gráfico
colors_dict = {
    "Precio_COP/kWh_0-7": '#1f77b4',  # Azul
    "Precio_COP/kWh_7-17": '#ff7f0e',  # Naranja
    "Precio_COP/kWh_17-23": '#2ca02c',  # Verde
    "Precio_COP/kWh_Dia": '#d62728',  # Rojo
    "Precio_Ponderado_COP/kWh": '#9467bd'  # Morado para el precio ponderado
}
fig = go.Figure()
for tipo in cols_precios:
    datos_filtrados = df_precios[tipo].dropna()
    fig.add_trace(
        go.Violin(
            y=datos_filtrados,
            name=tipo,
            box_visible=True,  # Mostrar caja dentro del violín
            meanline_visible=True,  # Mostrar línea de la media
            line_color='black',  # Color de la línea del violín
            fillcolor=colors_dict[tipo],  # Color de relleno según tipo
            opacity=0.75
        )
    )
fig.update_layout(
    title_text="Violin Plot de Precios",
    template="plotly_white",
    height=500,
    width=1000,
    yaxis_title="Precio (COP/kWh)"
)

fig.show()

In [13]:
# Revisar posible outlier
max_precio = df_precios["Precio_COP/kWh_Dia"].max()
print(f"\nEl precio máximo registrado en 'Precio_COP/kWh_Dia' es: {max_precio}")

display(df_precios[df_precios["Precio_COP/kWh_Dia"] == max_precio])

El precio máximo registrado en 'Precio_COP/kWh_Dia' es: 7235.163799999999

,Fecha,Precio_COP/kWh_0-7,Precio_COP/kWh_7-17,Precio_COP/kWh_17-23,Precio_COP/kWh_Dia,Precio_Ponderado_COP/kWh
273,2024-09-30,7235.1638,7235.1638,7235.1638,7235.1638,7235.1668

Este día se activó el estatuto de desabastecimiento, haciendo que para el 30 de septiembre de 2024 el precio llegara a esos niveles (más del 700% versus el día aneterior).

#### **Demanda**

In [14]:
# Cargar datos de demanda
df_demanda = pd.read_csv(SILVER_DATA_PATH + dict_files["demanda"], parse_dates=["Fecha"])
df_demanda["Tipo"] = "Demanda Total"

df_demanda_comprador = pd.read_csv(SILVER_DATA_PATH + dict_files["demanda_comprador"], parse_dates=["Fecha"])
df_demanda_comprador["Tipo"] = "Demanda Comprador"

df_demanda = pd.concat([df_demanda, df_demanda_comprador], axis=0)

# Filtrar por rango de fechas
mask = (df_demanda["Fecha"] >= start_date) & (df_demanda["Fecha"] <= end_date)
df_demanda = df_demanda.loc[mask]

# Forma del DataFrame
print(f"El DataFrame de demanda tiene {df_demanda.shape[0]} filas y {df_demanda.shape[1]} columnas.")

# Revisar las primeras filas del DataFrame
display(df_demanda.head())

El DataFrame de demanda tiene 1524 filas y 6 columnas.

,Fecha,Demanda_kWh_0-7,Demanda_kWh_7-17,Demanda_kWh_17-23,Demanda_kWh_Dia,Tipo
0,2024-01-01,54643293.94,64240594.05,56064773.70,1.749487e+08,Demanda Total
1,2024-01-02,57013232.43,81067177.66,64638105.93,2.027185e+08,Demanda Total
2,2024-01-03,61188695.23,85372974.57,67273522.47,2.138352e+08,Demanda Total
3,2024-01-04,62940795.31,86915531.57,68520455.08,2.183768e+08,Demanda Total
4,2024-01-05,63973370.58,87838187.90,68331839.33,2.201434e+08,Demanda Total

In [15]:
# Revisar la estructura del DataFrame
df_demanda.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1524 entries, 0 to 761
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Fecha              1524 non-null   datetime64[ns]
 1   Demanda_kWh_0-7    1524 non-null   float64
 2   Demanda_kWh_7-17   1524 non-null   float64
 3   Demanda_kWh_17-23  1524 non-null   float64
 4   Demanda_kWh_Dia    1524 non-null   float64
 5   Tipo               1524 non-null   object
dtypes: datetime64[ns](1), float64(4), object(1)
memory usage: 83.3+ KB

In [16]:
# Revisar si hay valores nulos
print("\nValores nulos por columna:")
display(df_demanda.isnull().sum())

Valores nulos por columna:

Fecha                0
Demanda_kWh_0-7      0
Demanda_kWh_7-17     0
Demanda_kWh_17-23    0
Demanda_kWh_Dia      0
Tipo                 0
dtype: int64

In [17]:
# Estadísticas descriptivas, histograma y violin plot para cada tipo de demanda
cols_analyze = [x for x in df_demanda.columns if x not in ["Tipo"]]
for tipo in df_demanda["Tipo"].unique():
    print(f"\nEstadísticas para demanda de tipo: {tipo}")
    temp_df = df_demanda[df_demanda["Tipo"] == tipo]
    display(temp_df[cols_analyze].describe())

    cols_demanda = [x for x in temp_df.columns if x not in ["Fecha", "Tipo"]]
    for col in cols_demanda:
        # 1. Crear la estructura de la figura (1 fila, 2 columnas)
        datos_filtrados = temp_df[col].dropna() # Asegurarse de no incluir NaN en los gráficos
        fig = make_subplots(
            rows=1, cols=1,
            subplot_titles=(f"Histograma de {col} - {tipo}")
        )

        # 2. Agregar el Histograma (Columna 1)
        # Nota: Plotly puro no trae la curva KDE automática como Seaborn, 
        # pero el histograma interactivo es muy potente.
        fig.add_trace(
            go.Histogram(
                x=datos_filtrados,
                name="Histograma",
                marker_color='#1f77b4',  # Un azul estándar
                opacity=0.75
            ),
            row=1, col=1
        )

        # 3. Actualizar el diseño general (Layout)
        fig.update_layout(
            title_text=f"Análisis de Distribución - {col} - {tipo}",
            showlegend=False,           # Ocultamos la leyenda para limpiar la vista
            template="plotly_white",    # Fondo blanco estilo Seaborn
            height=500,                 # Altura similar a figsize=(10,4)
            width=500
        )

        # Etiquetas de los ejes
        fig.update_xaxes(title_text="Demanda (kWh)", row=1, col=1)
        fig.update_yaxes(title_text="Frecuencia", row=1, col=1)

        fig.show()

Estadísticas para demanda de tipo: Demanda Total

,Fecha,Demanda_kWh_0-7,Demanda_kWh_7-17,Demanda_kWh_17-23,Demanda_kWh_Dia
count,762,7.620000e+02,7.620000e+02,7.620000e+02,7.620000e+02
mean,2025-01-15 12:00:00,6.612726e+07,8.950950e+07,7.047486e+07,2.261116e+08
min,2024-01-01 00:00:00,5.464329e+07,6.391227e+07,5.606477e+07,1.749487e+08
25%,2024-07-09 06:00:00,6.423122e+07,8.699654e+07,6.804307e+07,2.200907e+08
50%,2025-01-15 12:00:00,6.662044e+07,9.186601e+07,7.121414e+07,2.295100e+08
75%,2025-07-24 18:00:00,6.839832e+07,9.432709e+07,7.315971e+07,2.355526e+08
max,2026-01-31 00:00:00,7.231308e+07,9.929398e+07,7.756340e+07,2.487806e+08
std,NaN,3.252861e+06,6.854263e+06,3.793907e+06,1.344241e+07

Estadísticas para demanda de tipo: Demanda Comprador

,Fecha,Demanda_kWh_0-7,Demanda_kWh_7-17,Demanda_kWh_17-23,Demanda_kWh_Dia
count,762,7.620000e+02,7.620000e+02,7.620000e+02,7.620000e+02
mean,2025-01-15 12:00:00,3.616954e+06,3.626369e+06,3.187533e+06,1.043086e+07
min,2024-01-01 00:00:00,2.519790e+06,2.331331e+06,2.324448e+06,7.660018e+06
25%,2024-07-09 06:00:00,3.329877e+06,3.339023e+06,2.932723e+06,9.625874e+06
50%,2025-01-15 12:00:00,3.556551e+06,3.574166e+06,3.140097e+06,1.023276e+07
75%,2025-07-24 18:00:00,3.846421e+06,3.859215e+06,3.393721e+06,1.107474e+07
max,2026-01-31 00:00:00,4.675796e+06,4.910133e+06,4.146912e+06,1.370134e+07
std,NaN,3.807077e+05,4.123666e+05,3.418665e+05,1.110864e+06

In [18]:
# Violin plot para cada tipo de demanda en un sólo gráfico
colors_dict = {
    "Demanda_kWh_0-7": '#1f77b4',  # Azul
    "Demanda_kWh_7-17": '#ff7f0e',  # Naranja
    "Demanda_kWh_17-23": '#2ca02c',  # Verde
    "Demanda_kWh_Dia": '#d62728',  # Rojo
}

for tipo in df_demanda["Tipo"].unique():
    cols_demanda = [x for x in df_demanda.columns if x not in ["Fecha", "Tipo"]]
    fig = go.Figure()
    for dem in cols_demanda:
        datos_filtrados = df_demanda[df_demanda["Tipo"] == tipo][dem].dropna()
        fig.add_trace(
            go.Violin(
                y=datos_filtrados,
                name=dem,
                box_visible=True,  # Mostrar caja dentro del violín
                meanline_visible=True,  # Mostrar línea de la media
                line_color='black',  # Color de la línea del violín
                fillcolor=colors_dict[dem],  # Color de relleno según tipo
                opacity=0.75
            )
        )
    fig.update_layout(
        title_text=f"Violin Plot de Demanda - {tipo}",
        template="plotly_white",
        height=500,
        width=1000,
        yaxis_title="Demanda (kWh)"
    )

    fig.show()

#### **Aportes hídricos**

In [19]:
# Cargar datos de aportes hídricos
df_aportes = pd.read_csv(SILVER_DATA_PATH + dict_files["aportes_hidricos"], parse_dates=["Fecha"])

# Filtrar por rango de fechas
mask = (df_aportes["Fecha"] >= start_date) & (df_aportes["Fecha"] <= end_date)
df_aportes = df_aportes.loc[mask]

# Forma del DataFrame
print(f"El DataFrame de aportes hídricos tiene {df_aportes.shape[0]} filas y {df_aportes.shape[1]} columnas.")

# Revisar las primeras filas del DataFrame
display(df_aportes.head())

El DataFrame de aportes hídricos tiene 762 filas y 2 columnas.

       Fecha  AportesHidricos_GWh
0 2024-01-01             227.9060
1 2024-01-02             214.8830
2 2024-01-03             209.4194
3 2024-01-04             193.0248
4 2024-01-05             188.4468

In [20]:
# Revisar la estructura del DataFrame
print(df_aportes.info())

<class 'pandas.core.frame.DataFrame'>
Index: 762 entries, 0 to 761
Data columns (total 2 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Fecha                762 non-null    datetime64[ns]
 1   AportesHidricos_GWh  762 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 17.9 KB
None

In [21]:
# Revisar si hay valores nulos
print("\nValores nulos por columna:")
print(df_aportes.isnull().sum())

Valores nulos por columna:
Fecha                  0
AportesHidricos_GWh    0
dtype: int64

In [22]:
# Estadísticas descriptivas, histograma y violin plot
print(f"\nEstadísticas para los datos de aportes hídricos:")
display(df_aportes.describe())

# 1. Crear la estructura de la figura (1 fila, 2 columnas)
datos_filtrados = df_aportes["AportesHidricos_GWh"]
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=(f"Histograma de Aportes Hídricos", f"Violin Plot de Aportes Hídricos")
)

# 2. Agregar el Histograma (Columna 1)
# Nota: Plotly puro no trae la curva KDE automática como Seaborn, 
# pero el histograma interactivo es muy potente.
fig.add_trace(
    go.Histogram(
        x=datos_filtrados,
        name="Histograma",
        marker_color='#1f77b4',  # Un azul estándar
        opacity=0.75
    ),
    row=1, col=1
)

# 3. Agregar el Violin Plot (Columna 2)
fig.add_trace(
    go.Violin(
        x=datos_filtrados,
        name="Violin",
        box_visible=True,       # Muestra el boxplot adentro (como seaborn)
        meanline_visible=True,  # Muestra la línea de la media
        points='all',           # Opcional: muestra todos los puntos de datos (jitter)
        line_color='#ff7f0e',   # Un naranja para contrastar
        orientation='h'         # Horizontal (igual que sns.violinplot(x=...))
    ),
    row=1, col=2
)

# 4. Actualizar el diseño general (Layout)
fig.update_layout(
    title_text=f"Análisis de Distribución - Aportes Hídricos",
    showlegend=False,           # Ocultamos la leyenda para limpiar la vista
    template="plotly_white",    # Fondo blanco estilo Seaborn
    height=500,                 # Altura similar a figsize=(10,4)
    width=500
)

# Etiquetas de los ejes
fig.update_xaxes(title_text="Aportes Hídricos (GWh)", row=1, col=1)
fig.update_yaxes(title_text="Frecuencia", row=1, col=1)
fig.update_xaxes(title_text="Aportes Hídricos (GWh)", row=1, col=2)

fig.show()

Estadísticas para los datos de aportes hídricos:

                     Fecha  AportesHidricos_GWh
count                  762           762.000000
mean   2025-01-15 12:00:00           415.949625
min    2024-01-01 00:00:00           111.649400
25%    2024-07-09 06:00:00           264.774850
50%    2025-01-15 12:00:00           385.271139
75%    2025-07-24 18:00:00           522.406600
max    2026-01-31 00:00:00          1286.808400
std                    NaN           211.406248

#### **Niveles de embalses**

In [23]:
# Cargar datos de niveles de embalse
df_niveles = pd.read_csv(SILVER_DATA_PATH + dict_files["niveles_embalse"], parse_dates=["Fecha"])

# Filtrar por rango de fechas
mask = (df_niveles["Fecha"] >= start_date) & (df_niveles["Fecha"] <= end_date)
df_niveles = df_niveles.loc[mask]

# Forma del DataFrame
print(f"El DataFrame de niveles de embalse tiene {df_niveles.shape[0]} filas y {df_niveles.shape[1]} columnas.")

# Revisar las primeras filas del DataFrame
display(df_niveles.head())

El DataFrame de niveles de embalse tiene 762 filas y 2 columnas.

       Fecha  NivelEmbalse
0 2024-01-01  1.222112e+10
1 2024-01-02  1.218586e+10
2 2024-01-03  1.216112e+10
3 2024-01-04  1.210052e+10
4 2024-01-05  1.203630e+10

In [24]:
# Revisar la estructura del DataFrame
df_niveles.info()

<class 'pandas.core.frame.DataFrame'>
Index: 762 entries, 0 to 761
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fecha         762 non-null    datetime64[ns]
 1   NivelEmbalse  762 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 17.9 KB

In [25]:
# Revisar si hay valores nulos
print("\nValores nulos por columna:")
display(df_niveles.isnull().sum())

Valores nulos por columna:

Fecha           0
NivelEmbalse    0
dtype: int64

In [26]:
# Estadísticas descriptivas, histograma y violin plot
print(f"\nEstadísticas para los datos de los niveles de los embalses:")
display(df_niveles.describe())

# 1. Crear la estructura de la figura (1 fila, 2 columnas)
datos_filtrados = df_niveles["NivelEmbalse"]
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=(f"Histograma de Nivel de Embalse", f"Violin Plot de Nivel de Embalse")
)

# 2. Agregar el Histograma (Columna 1)
# Nota: Plotly puro no trae la curva KDE automática como Seaborn, 
# pero el histograma interactivo es muy potente.
fig.add_trace(
    go.Histogram(
        x=datos_filtrados,
        name="Histograma",
        marker_color='#1f77b4',  # Un azul estándar
        opacity=0.75
    ),
    row=1, col=1
)

# 3. Agregar el Violin Plot (Columna 2)
fig.add_trace(
    go.Violin(
        x=datos_filtrados,
        name="Violin",
        box_visible=True,       # Muestra el boxplot adentro (como seaborn)
        meanline_visible=True,  # Muestra la línea de la media
        points='all',           # Opcional: muestra todos los puntos de datos (jitter)
        line_color='#ff7f0e',   # Un naranja para contrastar
        orientation='h'         # Horizontal (igual que sns.violinplot(x=...))
    ),
    row=1, col=2
)

# 4. Actualizar el diseño general (Layout)
fig.update_layout(
    title_text=f"Análisis de Distribución - Nivel de Embalse",
    showlegend=False,           # Ocultamos la leyenda para limpiar la vista
    template="plotly_white",    # Fondo blanco estilo Seaborn
    height=500,                 # Altura similar a figsize=(10,4)
    width=1000
)

# Etiquetas de los ejes
fig.update_xaxes(title_text="Nivel de Embalse", row=1, col=1)
fig.update_yaxes(title_text="Frecuencia", row=1, col=1)
fig.update_xaxes(title_text="Nivel de Embalse", row=1, col=2)

fig.show()

Estadísticas para los datos de los niveles de los embalses:

                     Fecha  NivelEmbalse
count                  762  7.620000e+02
mean   2025-01-15 12:00:00  1.082642e+10
min    2024-01-01 00:00:00  4.958518e+09
25%    2024-07-09 06:00:00  9.153008e+09
50%    2025-01-15 12:00:00  1.041734e+10
75%    2025-07-24 18:00:00  1.378513e+10
max    2026-01-31 00:00:00  1.690569e+10
std                    NaN  2.676235e+09

In [27]:
# Revisar posible outlier
max_nivel = df_niveles["NivelEmbalse"].max()
print(f"\nEl nivel máximo registrado en 'NivelEmbalse' es: {max_nivel}")

display(df_niveles[df_niveles["NivelEmbalse"] == max_nivel])

El nivel máximo registrado en 'NivelEmbalse' es: 16905690000.0

         Fecha  NivelEmbalse
698 2025-11-29  1.690569e+10

El día 29 de noviembre ocurrió lo siguiente:
1. Lluvias torrenciales y Fenómenos Climáticos: El 29 de noviembre de 2025, Colombia (particularmente en la región Caribe y el departamento de Córdoba) enfrentó una jornada de lluvias excepcionalmente fuertes. Estas precipitaciones causaron un aumento crítico en los niveles de varios embalses.

2. Emergencia en el Embalse Urrá I: En esa fecha exacta, se declaró la Alerta Naranja debido al riesgo inminente de rebose del embalse Urrá I. Las autoridades y empresas como XM estuvieron bajo máxima presión para monitorear los niveles, lo que pudo haber generado errores en la consolidación o reporte de datos en tiempo real debido a la magnitud de la emergencia y posibles fallas en sensores por las tormentas.

3. Inundaciones en la Cuenca del Sinú: El incremento acelerado reportado coincidió con el desbordamiento de varios ríos, lo que obligó a activar protocolos de emergencia en ocho municipios de Córdoba.

#### **Disponibilidad**

In [28]:
# Cargar datos de disponibilidad
df_disponibilidad = pd.read_csv(SILVER_DATA_PATH + dict_files["disponibilidad"], parse_dates=["Fecha"])

# Filtrar por rango de fechas
mask = (df_disponibilidad["Fecha"] >= start_date) & (df_disponibilidad["Fecha"] <= end_date)
df_disponibilidad = df_disponibilidad.loc[mask]

# Forma del DataFrame
print(f"El DataFrame de disponibilidad tiene {df_disponibilidad.shape[0]} filas y {df_disponibilidad.shape[1]} columnas.")

# Revisar las primeras filas del DataFrame
display(df_disponibilidad.head())

El DataFrame de disponibilidad tiene 762 filas y 5 columnas.

,Fecha,Disponibilidad_kWh_0-7,Disponibilidad_kWh_7-17,Disponibilidad_kWh_17-23,Disponibilidad_kWh_Dia
0,2024-01-01,1.378181e+08,1.605294e+08,1.209199e+08,4.192674e+08
1,2024-01-02,1.351606e+08,1.559575e+08,1.183149e+08,4.094330e+08
2,2024-01-03,1.335592e+08,1.560147e+08,1.175417e+08,4.071155e+08
3,2024-01-04,1.305546e+08,1.526019e+08,1.150303e+08,3.981869e+08
4,2024-01-05,1.320421e+08,1.546916e+08,1.159019e+08,4.026356e+08

In [29]:
# Revisar la estructura del DataFrame
df_disponibilidad.info()

<class 'pandas.core.frame.DataFrame'>
Index: 762 entries, 0 to 761
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Fecha                     762 non-null    datetime64[ns]
 1   Disponibilidad_kWh_0-7    762 non-null    float64
 2   Disponibilidad_kWh_7-17   762 non-null    float64
 3   Disponibilidad_kWh_17-23  762 non-null    float64
 4   Disponibilidad_kWh_Dia    762 non-null    float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 35.7 KB

In [30]:
# Revisar si hay valores nulos
print("\nValores nulos por columna:")
display(df_disponibilidad.isnull().sum())

Valores nulos por columna:

Fecha                       0
Disponibilidad_kWh_0-7      0
Disponibilidad_kWh_7-17     0
Disponibilidad_kWh_17-23    0
Disponibilidad_kWh_Dia      0
dtype: int64

In [31]:
# Estadísticas descriptivas, histograma y violin plot para disponibilidad
print(f"\nEstadísticas para los datos de disponibilidad:")
display(df_disponibilidad.describe())

cols_disponibilidad = [x for x in df_disponibilidad.columns if x not in ["Fecha"]]
for col in cols_disponibilidad:
    # 1. Crear la estructura de la figura (1 fila, 2 columnas)
    datos_filtrados = df_disponibilidad[col].dropna() # Asegurarse de no incluir NaN en los gráficos
    fig = make_subplots(
        rows=1, cols=1,
        subplot_titles=(f"Histograma de {col}", f"Violin Plot de {col}")
    )

    # 2. Agregar el Histograma (Columna 1)
    # Nota: Plotly puro no trae la curva KDE automática como Seaborn, 
    # pero el histograma interactivo es muy potente.
    fig.add_trace(
        go.Histogram(
            x=datos_filtrados,
            name="Histograma",
            marker_color='#1f77b4',  # Un azul estándar
            opacity=0.75
        ),
        row=1, col=1
    )

    # 3. Actualizar el diseño general (Layout)
    fig.update_layout(
        title_text=f"Análisis de Distribución - {col}",
        showlegend=False,           # Ocultamos la leyenda para limpiar la vista
        template="plotly_white",    # Fondo blanco estilo Seaborn
        height=500,                 # Altura similar a figsize=(10,4)
        width=500
    )

    # Etiquetas de los ejes
    fig.update_xaxes(title_text="Disponibilidad (kWh)", row=1, col=1)
    fig.update_yaxes(title_text="Frecuencia", row=1, col=1)

    fig.show()

Estadísticas para los datos de disponibilidad:

,Fecha,Disponibilidad_kWh_0-7,Disponibilidad_kWh_7-17,Disponibilidad_kWh_17-23,Disponibilidad_kWh_Dia
count,762,7.620000e+02,7.620000e+02,7.620000e+02,7.620000e+02
mean,2025-01-15 12:00:00,1.224060e+08,1.472415e+08,1.086163e+08,3.782638e+08
min,2024-01-01 00:00:00,1.034929e+08,1.286985e+08,9.573596e+07,3.322291e+08
25%,2024-07-09 06:00:00,1.171583e+08,1.413392e+08,1.045046e+08,3.633777e+08
50%,2025-01-15 12:00:00,1.224921e+08,1.463390e+08,1.081499e+08,3.768147e+08
75%,2025-07-24 18:00:00,1.273263e+08,1.518156e+08,1.120598e+08,3.912655e+08
max,2026-01-31 00:00:00,1.435787e+08,1.776768e+08,1.264400e+08,4.455702e+08
std,NaN,6.984961e+06,8.444018e+06,5.470602e+06,2.027347e+07

In [32]:
# Violin plot para cada tipo de disponibilidad en un sólo gráfico
colors_dict = {
    "Disponibilidad_kWh_0-7": '#1f77b4',  # Azul
    "Disponibilidad_kWh_7-17": '#ff7f0e',  # Naranja
    "Disponibilidad_kWh_17-23": '#2ca02c',  # Verde
    "Disponibilidad_kWh_Dia": '#d62728',  # Rojo
}

cols_disponibilidad = [x for x in df_disponibilidad.columns if x not in ["Fecha", "Tipo"]]
fig = go.Figure()
for dem in cols_disponibilidad:
    datos_filtrados = df_disponibilidad[dem].dropna()
    fig.add_trace(
        go.Violin(
            y=datos_filtrados,
            name=dem,
            box_visible=True,  # Mostrar caja dentro del violín
            meanline_visible=True,  # Mostrar línea de la media
            line_color='black',  # Color de la línea del violín
            fillcolor=colors_dict[dem],  # Color de relleno según tipo
            opacity=0.75
        )
    )
fig.update_layout(
    title_text=f"Violin Plot de Disponibilidad",
    template="plotly_white",
    height=500,
    width=1000,
    yaxis_title="Disponibilidad (kWh)"
)

fig.show()

#### **Generación**

In [33]:
# Cargar datos de generación
df_generacion = pd.read_csv(SILVER_DATA_PATH + dict_files["generacion"], parse_dates=["Fecha"])

# Filtrar por rango de fechas
mask = (df_generacion["Fecha"] >= start_date) & (df_generacion["Fecha"] <= end_date)
df_generacion = df_generacion.loc[mask]

# Forma del DataFrame
print(f"El DataFrame de generación tiene {df_generacion.shape[0]} filas y {df_generacion.shape[1]} columnas.")

# Revisar las primeras filas del DataFrame
display(df_generacion.head())

El DataFrame de generación tiene 762 filas y 7 columnas.

,Fecha,Generacion_Cogenerador_kWh,Generacion_Eolica_kWh,Generacion_Hidraulica_kWh,Generacion_Solar_kWh,Generacion_Termica_kWh,Generacion_Total_kWh
0,2024-01-01,357159.25,473795.05,1.438421e+08,6384628.58,25116512.59,1.761742e+08
1,2024-01-02,562877.06,423687.71,1.622771e+08,6947627.66,36498096.07,2.067094e+08
2,2024-01-03,1179331.32,391955.20,1.651038e+08,7424880.76,40751417.04,2.148514e+08
3,2024-01-04,1437006.35,482435.75,1.601428e+08,7443663.23,49910444.26,2.194164e+08
4,2024-01-05,1818277.52,650878.14,1.593047e+08,7135847.51,52357284.27,2.212670e+08

In [34]:
# Revisar la estructura del DataFrame
df_generacion.info()

<class 'pandas.core.frame.DataFrame'>
Index: 762 entries, 0 to 761
Data columns (total 7 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Fecha                       762 non-null    datetime64[ns]
 1   Generacion_Cogenerador_kWh  762 non-null    float64
 2   Generacion_Eolica_kWh       762 non-null    float64
 3   Generacion_Hidraulica_kWh   762 non-null    float64
 4   Generacion_Solar_kWh        762 non-null    float64
 5   Generacion_Termica_kWh      762 non-null    float64
 6   Generacion_Total_kWh        762 non-null    float64
dtypes: datetime64[ns](1), float64(6)
memory usage: 47.6 KB

In [35]:
# REvisar si hay valores nulos
print("\nValores nulos por columna:")
display(df_generacion.isnull().sum())

Valores nulos por columna:

Fecha                         0
Generacion_Cogenerador_kWh    0
Generacion_Eolica_kWh         0
Generacion_Hidraulica_kWh     0
Generacion_Solar_kWh          0
Generacion_Termica_kWh        0
Generacion_Total_kWh          0
dtype: int64

In [36]:
# Estadísticas descriptivas, histograma y violin plot para generacion
print(f"\nEstadísticas para los datos de generacion:")
display(df_generacion.describe())

cols_generacion = [x for x in df_generacion.columns if x not in ["Fecha"]]
for col in cols_generacion:
    # 1. Crear la estructura de la figura (1 fila, 2 columnas)
    datos_filtrados = df_generacion[col].dropna() # Asegurarse de no incluir NaN en los gráficos
    fig = make_subplots(
        rows=1, cols=1,
        subplot_titles=(f"Histograma de {col}", f"Violin Plot de {col}")
    )

    # 2. Agregar el Histograma (Columna 1)
    # Nota: Plotly puro no trae la curva KDE automática como Seaborn, 
    # pero el histograma interactivo es muy potente.
    fig.add_trace(
        go.Histogram(
            x=datos_filtrados,
            name="Histograma",
            marker_color='#1f77b4',  # Un azul estándar
            opacity=0.75
        ),
        row=1, col=1
    )

    # 4. Actualizar el diseño general (Layout)
    fig.update_layout(
        title_text=f"Análisis de Distribución - {col}",
        showlegend=False,           # Ocultamos la leyenda para limpiar la vista
        template="plotly_white",    # Fondo blanco estilo Seaborn
        height=500,                 # Altura similar a figsize=(10,4)
        width=500
    )

    # Etiquetas de los ejes
    fig.update_xaxes(title_text="Generación (kWh)", row=1, col=1)
    fig.update_yaxes(title_text="Frecuencia", row=1, col=1)

    fig.show()

Estadísticas para los datos de generacion:

,Fecha,Generacion_Cogenerador_kWh,Generacion_Eolica_kWh,Generacion_Hidraulica_kWh,Generacion_Solar_kWh,Generacion_Termica_kWh,Generacion_Total_kWh
count,762,7.620000e+02,762.000000,7.620000e+02,7.620000e+02,7.620000e+02,7.620000e+02
mean,2025-01-15 12:00:00,2.346914e+06,430234.724528,1.686186e+08,1.062933e+07,4.758335e+07,2.296084e+08
min,2024-01-01 00:00:00,1.521932e+05,0.000000,7.821828e+07,3.595164e+06,1.681684e+07,1.761742e+08
25%,2024-07-09 06:00:00,2.129190e+06,313351.200000,1.496090e+08,8.913056e+06,2.551069e+07,2.221504e+08
50%,2025-01-15 12:00:00,2.430645e+06,467329.450000,1.736384e+08,1.050772e+07,3.701808e+07,2.324798e+08
75%,2025-07-24 18:00:00,2.660515e+06,573167.415000,1.925208e+08,1.231641e+07,6.502641e+07,2.399545e+08
max,2026-01-31 00:00:00,7.127830e+06,817870.000000,2.144934e+08,1.903674e+07,1.197379e+08,2.560234e+08
std,NaN,5.538145e+05,190515.435914,2.830644e+07,2.432269e+06,2.690249e+07,1.386271e+07

In [37]:
df_generacion.columns

Index(['Fecha', 'Generacion_Cogenerador_kWh', 'Generacion_Eolica_kWh',
       'Generacion_Hidraulica_kWh', 'Generacion_Solar_kWh',
       'Generacion_Termica_kWh', 'Generacion_Total_kWh'],
      dtype='object')

In [38]:
# Violin plot para cada tipo de generación en un sólo gráfico
colors_dict = {
    "Generacion_Cogenerador_kWh": '#1f77b4',  # Azul
    "Generacion_Eolica_kWh": '#ff7f0e',  # Naranja
    "Generacion_Hidraulica_kWh": '#2ca02c',  # Verde
    "Generacion_Solar_kWh": '#d62728',  # Rojo
    "Generacion_Termica_kWh": '#9467bd'  # Morado para la generación térmica
}

cols_generacion = [x for x in colors_dict.keys()]
fig = go.Figure()
for dem in cols_generacion:
    datos_filtrados = df_generacion[dem].dropna()
    fig.add_trace(
        go.Violin(
            y=datos_filtrados,
            name=dem,
            box_visible=True,  # Mostrar caja dentro del violín
            meanline_visible=True,  # Mostrar línea de la media
            line_color='black',  # Color de la línea del violín
            fillcolor=colors_dict[dem],  # Color de relleno según tipo
            opacity=0.75
        )
    )
fig.update_layout(
    title_text=f"Violin Plot de Generación por Tipo",
    template="plotly_white",
    height=500,
    width=1000,
    yaxis_title="Generación (kWh)"
)

fig.show()

In [39]:
# % Generación por tipo por año y mes
df_generacion_group = df_generacion.copy()

df_generacion_group["Año"] = df_generacion_group["Fecha"].dt.year

cols_generacion = [x for x in df_generacion_group.columns if x not in ["Fecha", "Año", "Generacion_Total_kWh"]]
df_generacion_group2 = df_generacion_group.groupby(["Año"])[cols_generacion].sum().reset_index()
for col in df_generacion_group2.columns:
    if col in cols_generacion:
        df_generacion_group2[f"%_{col}"] = ((df_generacion_group2[col] / df_generacion_group2[cols_generacion].sum(axis=1)) * 100).round(2)
        df_generacion_group[f"%_{col}"] = ((df_generacion_group[col] / df_generacion_group[cols_generacion].sum(axis=1)) * 100).round(2)

cols_porcentaje = [x for x in df_generacion_group2.columns if x.startswith("%_")]

print("\nPorcentaje de generación por tipo por año:")
display(df_generacion_group2[["Año"] + cols_porcentaje])

# Gráfico de líneas para el porcentaje de generación por tipo a lo largo del tiempo
colors_dict = {
    "%_Generacion_Cogenerador_kWh": '#1f77b4',  # Azul
    "%_Generacion_Eolica_kWh": '#ff7f0e',  # Naranja
    "%_Generacion_Hidraulica_kWh": '#2ca02c',  # Verde
    "%_Generacion_Solar_kWh": '#d62728',  # Rojo
    "%_Generacion_Termica_kWh": '#9467bd'  # Morado para la generación térmica
}

fig = go.Figure()
for col in cols_porcentaje:
    fig.add_trace(
        go.Scatter(
            x=df_generacion_group["Fecha"],
            y=df_generacion_group[col],
            mode='lines+markers',
            name=col.replace("%_", ""),
            line=dict(color=colors_dict[col], width=2)
        )
    )
fig.update_layout(
    title="Porcentaje de Generación por Tipo a lo largo del Tiempo",
    xaxis_title="Fecha",
    yaxis_title="Porcentaje (%)",
    template="plotly_white",
    height=500,
    width=1000,
    legend=dict(
        orientation="h",
        yanchor="bottom",
        y=-0.4,
        xanchor="center",
        x=0.5
    )
)

fig.show()

Porcentaje de generación por tipo por año:

,Año,%_Generacion_Cogenerador_kWh,%_Generacion_Eolica_kWh,%_Generacion_Hidraulica_kWh,%_Generacion_Solar_kWh,%_Generacion_Termica_kWh
0,2024,1.01,0.18,65.42,3.97,29.42
1,2025,1.04,0.19,80.68,5.16,12.93
2,2026,0.99,0.26,81.12,6.05,11.58

In [40]:
# Posible outlier en generación del Cogenerador
max_cogenerador = df_generacion["Generacion_Cogenerador_kWh"].max()

print(f"\nLa generación máxima registrada en 'Generacion_Cogenerador_kWh' es: {max_cogenerador}")

display(df_generacion[df_generacion["Generacion_Cogenerador_kWh"] == max_cogenerador])

La generación máxima registrada en 'Generacion_Cogenerador_kWh' es: 7127830.0

,Fecha,Generacion_Cogenerador_kWh,Generacion_Eolica_kWh,Generacion_Hidraulica_kWh,Generacion_Solar_kWh,Generacion_Termica_kWh,Generacion_Total_kWh
716,2025-12-17,7127830.0,575800.0,197066300.0,13535310.0,35690810.0,253996050.0

El día 17 de diciembre de 2025 se presenta una posible anomalía en la generación por parte de los Cogeneradores. Consultando, esta posible anomalía se puede deber a:

1. Compensación por baja generación hidráulica: El análisis de los datos muestra que el 17 de diciembre la generación hidráulica cayó de 202 GWh a 197 GWh. Para mantener el equilibrio del sistema, el despacho nacional solicitó un aumento en la entrega de excedentes de fuentes no hidráulicas.

2. Temporada de Zafra (Cosecha): Diciembre es un mes de alta intensidad en la cosecha de caña de azúcar en Colombia. En esta fecha específica, los ingenios alcanzaron su máxima capacidad de entrega de excedentes debido a la abundancia de biomasa (bagazo) disponible y a la necesidad del sistema de suplir la demanda de fin de año.

3. Prueba de Disponibilidad: Técnicamente, este tipo de picos aislados de un solo día también suelen corresponder a "Pruebas de Disponibilidad" exigidas por XM. Los cogeneradores deben demostrar periódicamente que pueden alcanzar su capacidad máxima declarada para asegurar su remuneración por Cargo por Confiabilidad.

### **Análisis bivariado**

1. Grafico de líneas entre los precios y los tipos de contratos, para diez vencimientos por contratos
2. Análisis de correlación entre las variables, por tipo de contrato, para diez vencimientos
  - Hacer el análisis de correlación junto con gráficos de líneas, pero antes aplicar una normalización