### **Librerías**

In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from plotly.subplots import make_subplots

ModuleNotFoundError: No module named 'plotly'

### **Parámetros**

In [2]:
os.chdir("/Users/juanchacon/Library/Mobile Documents/com~apple~CloudDocs/GitHub/bot_futuros")

SILVER_DATA_PATH = os.getcwd() + "/data/silver/"

dict_files = {
    "futuros": "precios_FUTUROS.csv",
    "precios": "datos_PRECIOS.csv",
    "precios_ponderados": "datos_PRECIOS_PONDERADOS.csv",
    "demanda": "datos_DEMANDA.csv",
    "demanda_comprador": "datos_DEMANDA_COMPRADOR.csv",
    "aportes_hidricos": "datos_APORTES_HIDRICOS.csv",
    "niveles_embalse": "datos_NIVELES_EMBALSE.csv",
    "generacion": "datos_GENERACION_REAL.csv",
    "disponibilidad": "datos_DISPONIBILIDAD_REAL.csv",
}

start_date = "2024-01-01"
end_date = "2026-01-31"

### **EDA**

#### **Futuros**

In [3]:
# Carga de datos
df_futuros = pd.read_csv(SILVER_DATA_PATH + dict_files["futuros"], parse_dates=["Fecha", "FechaVencimientoContrato"])

# Filtrar por rango de fechas
mask = (df_futuros["Fecha"] >= start_date) & (df_futuros["Fecha"] <= end_date)
df_futuros = df_futuros.loc[mask]

# Forma del DataFrame
print(f"El DataFrame de futuros tiene {df_futuros.shape[0]} filas y {df_futuros.shape[1]} columnas.")

# Revisar las primeras filas del DataFrame
display(df_futuros.head())

El DataFrame de futuros tiene 73296 filas y 7 columnas.

  Nemotecnico Tipo    Mes   Año      Fecha FechaVencimientoContrato  Precio
0     ELMF26F  ELM  Enero  2026 2026-01-02               2026-01-31  390.05
1     ELMF26F  ELM  Enero  2026 2026-01-05               2026-01-31  386.97
2     ELMF26F  ELM  Enero  2026 2026-01-06               2026-01-31  383.41
3     ELMF26F  ELM  Enero  2026 2026-01-07               2026-01-31  379.84
4     ELMF26F  ELM  Enero  2026 2026-01-08               2026-01-31  374.07

In [4]:
# Revisar la estructura del DataFrame
df_futuros.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73296 entries, 0 to 74735
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Nemotecnico               73296 non-null  object
 1   Tipo                      73296 non-null  object
 2   Mes                       73296 non-null  object
 3   Año                       73296 non-null  int64
 4   Fecha                     73296 non-null  datetime64[ns]
 5   FechaVencimientoContrato  73296 non-null  datetime64[ns]
 6   Precio                    73296 non-null  float64
dtypes: datetime64[ns](2), float64(1), int64(1), object(3)
memory usage: 4.5+ MB

In [ ]:
# Estadísticas descriptivas, histograma y violin plot para cada tipo de contrato
cols_analyze = ["Fecha", "FechaVencimientoContrato", "Precio"]
for tipo in df_futuros["Tipo"].unique():
    print(f"\nEstadísticas para contratos de tipo: {tipo}")
    display(df_futuros[df_futuros["Tipo"] == tipo][cols_analyze].describe())

    # Histograma
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    sns.histplot(df_futuros[df_futuros["Tipo"] == tipo]["Precio"], bins=30, kde=True)
    plt.title(f"Histograma de Precios - {tipo}")
    plt.xlabel("Precio")
    plt.ylabel("Frecuencia")

    # Violin plot
    plt.subplot(1, 2, 2)
    sns.violinplot(x=df_futuros[df_futuros["Tipo"] == tipo]["Precio"])
    plt.title(f"Violin Plot de Precios - {tipo}")
    plt.xlabel("Precio")
    plt.tight_layout()
    plt.show()

Estadísticas para contratos de tipo: ELM

,Fecha,FechaVencimientoContrato,Precio
count,36648,36648,36648.000000
mean,2025-01-14 02:12:57.996070656,2028-01-13 22:41:43.732809472,388.084391
min,2024-01-02 00:00:00,2024-01-31 00:00:00,110.000000
25%,2024-07-10 00:00:00,2026-06-30 00:00:00,360.000000
50%,2025-01-16 00:00:00,2027-12-31 00:00:00,377.315000
75%,2025-07-23 00:00:00,2029-06-30 00:00:00,409.342500
max,2026-01-30 00:00:00,2031-12-31 00:00:00,941.370000
std,NaN,NaN,56.568539

Estadísticas para contratos de tipo: MTB

,Fecha,FechaVencimientoContrato,Precio
count,12216,12216,12216.000000
mean,2025-01-14 02:12:57.996070656,2026-01-13 11:00:42.436149248,343.560368
min,2024-01-02 00:00:00,2024-01-31 00:00:00,111.930000
25%,2024-07-10 00:00:00,2025-05-31 00:00:00,310.002500
50%,2025-01-16 00:00:00,2025-12-31 00:00:00,336.370000
75%,2025-07-23 00:00:00,2026-08-31 00:00:00,367.780000
max,2026-01-30 00:00:00,2027-12-31 00:00:00,932.490000
std,NaN,NaN,80.914989

Estadísticas para contratos de tipo: DTB

,Fecha,FechaVencimientoContrato,Precio
count,12216,12216,12216.000000
mean,2025-01-14 02:12:57.996070656,2026-01-13 11:00:42.436149248,404.826023
min,2024-01-02 00:00:00,2024-01-31 00:00:00,119.150000
25%,2024-07-10 00:00:00,2025-05-31 00:00:00,367.640000
50%,2025-01-16 00:00:00,2025-12-31 00:00:00,398.080000
75%,2025-07-23 00:00:00,2026-08-31 00:00:00,436.710000
max,2026-01-30 00:00:00,2027-12-31 00:00:00,932.490000
std,NaN,NaN,89.540748

Estadísticas para contratos de tipo: NTB

,Fecha,FechaVencimientoContrato,Precio
count,12216,12216,12216.000000
mean,2025-01-14 02:12:57.996070656,2026-01-13 11:00:42.436149248,416.914098
min,2024-01-02 00:00:00,2024-01-31 00:00:00,137.660000
25%,2024-07-10 00:00:00,2025-05-31 00:00:00,376.600000
50%,2025-01-16 00:00:00,2025-12-31 00:00:00,409.490000
75%,2025-07-23 00:00:00,2026-08-31 00:00:00,445.550000
max,2026-01-30 00:00:00,2027-12-31 00:00:00,935.040000
std,NaN,NaN,91.561207