In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [99]:

# Ruta donde están tus archivos Excel
ruta = r"C:\Users\Jhon Fernando Tascón\Desktop\Jhon\Maestría\DATOS PROYECTO INTEGRADOR"

# --- ARCHIVO: Cierre.xlsx ---
cierre_elm = pd.read_excel(os.path.join(ruta, "Cierre.xlsx"), sheet_name="Precio cierre ELM",skiprows=1,usecols="A:CQ")
cierre_mtb = pd.read_excel(os.path.join(ruta, "Cierre.xlsx"), sheet_name="Precio cierre MTB",skiprows=1,usecols="A:AU")
cierre_dtb = pd.read_excel(os.path.join(ruta, "Cierre.xlsx"), sheet_name="Precio cierre DTB",skiprows=1,usecols="A:AU")
cierre_ntb = pd.read_excel(os.path.join(ruta, "Cierre.xlsx"), sheet_name="Precio cierre NTB",skiprows=1,usecols="A:AU")

# --- ARCHIVO: Convocatorias.xlsx ---
CONV = pd.read_excel("Convocatorias.xlsx", sheet_name="Resultados Convocatorias",skiprows=12,usecols="D:J")
REFE = pd.read_excel("Convocatorias.xlsx", sheet_name="Precios de referencia",skiprows=4,usecols="D:G")

# --- ARCHIVO: Neg_Electrónica.xlsx ---
neg_electronica = pd.read_excel(os.path.join(ruta, "Neg_Electrónica.xls"), sheet_name="Mejores Puntas")

# --- ARCHIVO: Neg_Mixta.xlsx ---
neg_mixta = pd.read_excel(os.path.join(ruta, "Neg_Mixta.xlsx"), sheet_name="Órdenes_Mixta")

# --- ARCHIVO: Ultimas.xlsx ---
ultimas = pd.read_excel(os.path.join(ruta, "Ultimas.xlsx"), sheet_name="Negociaciones",usecols="A:J")
resumen = pd.read_excel(os.path.join(ruta, "Ultimas.xlsx"), sheet_name="Resumen",skiprows=1,usecols="B:D")

# --- Confirmación de carga ---
print("✅ Archivos cargados correctamente:\n")
for nombre, df in {
    "Precio cierre ELM": cierre_elm,
    "Precio cierre MTB": cierre_mtb,
    "Precio cierre DTB": cierre_dtb,
    "Precio cierre NTB": cierre_ntb,
    "Neg_Electrónica": neg_electronica,
    "Neg_Mixta": neg_mixta,
    "Ultimas": ultimas,
    "Resumen": resumen
}.items():
    print(f"{nombre}: {df.shape[0]} filas × {df.shape[1]} columnas")

✅ Archivos cargados correctamente:

Precio cierre ELM: 458 filas × 95 columnas
Precio cierre MTB: 458 filas × 47 columnas
Precio cierre DTB: 458 filas × 47 columnas
Precio cierre NTB: 458 filas × 47 columnas
Neg_Electrónica: 10500 filas × 6 columnas
Neg_Mixta: 46 filas × 10 columnas
Ultimas: 370 filas × 10 columnas
Resumen: 26 filas × 3 columnas

**Negociación Electrónica**

In [16]:
neg_electronica.head()

,FECHA,CONTRATO,MEJOR PRECIO DE COMPRA (BID),CANTIDAD DE CONTRATOS CON EL MEJOR PRECIO DE COMPRA,MEJOR PRECIO DE VENTA (OFFER),CANTIDAD DE CONTRATOS CON EL MEJOR PRECIO DE VENTA
0,2024-01-02,ELMM25F,0,0,390,1
1,2024-01-02,ELMN25F,0,0,393,1
2,2024-01-02,ELMQ25F,0,0,400,1
3,2024-01-02,ELMU25F,0,0,400,1
4,2024-01-02,ELB2025F,0,0,556.5,24

**Negociación Mixta**

In [17]:
neg_mixta.head()

,FECHA,CONTRATOS,NEMOTÉCNICOS,CANTIDAD DE ENERGÍA EN COMPRA POR MES (kWh),MEJOR PRECIO DE COMPRA (BID),MEJOR PRECIO DE VENTA (OFFER),CANTIDAD DE ENERGÍA EN VENTA POR MES (kWh),.,TOTAL CANTIDAD DE ENERGÍA EXPUESTA EN COMPRA(KWh),TOTAL CANTIDAD DE ENERGÍA EXPUESTA EN VENTA (KWh)
0,2023-04-05,Abr-Jun 2023,ELMJ23F-ELMM23F,0,0,320.0,18000000.0,NaN,0,54000000
1,2023-09-21,Jun-Sep 2025,ELMM25F-ELMU25F,0,0,385.0,2160000.0,NaN,0,8640000
2,2023-09-22,Jun-Sep 2025,ELMM25F-ELMU25F,0,0,385.0,2160000.0,NaN,0,8640000
3,2023-09-25,Jun-Sep 2025,ELMM25F-ELMU25F,0,0,385.0,2160000.0,NaN,0,8640000
4,2023-09-26,Jun-Sep 2025,ELMM25F-ELMU25F,0,0,385.0,2160000.0,NaN,0,8640000

**Últimas negociaciones**

In [18]:
ultimas.head()

,Fecha,Instrumento,Contrato,Mes contrato,Precio,Cantidad,Monto,Carga total kWh,Negociación en bloque,Sesión de negociación,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,2024-01-17,ELM,ELMF25F,2025-01-01,420.0,30,4536000000,10800000,SI,Convocatoria,NaN,NaT,NaN
1,2024-01-17,ELM,ELMG25F,2025-02-01,420.0,30,4536000000,10800000,SI,Convocatoria,NaN,NaT,NaN
2,2024-01-17,ELM,ELMH25F,2025-03-01,420.0,30,4536000000,10800000,SI,Convocatoria,NaN,NaT,NaN
3,2024-01-17,ELM,ELMJ25F,2025-04-01,420.0,30,4536000000,10800000,SI,Convocatoria,NaN,NaT,NaN
4,2024-01-17,ELM,ELMK25F,2025-05-01,420.0,30,4536000000,10800000,SI,Convocatoria,NaN,NaT,NaN

**ACÁ SE HACE EL AJUSTE DE LA TRANSFORMACIÓN DE LOS DATASETS DE PRECIOS DE CIERRE DE MTB NTB DTB Y ELN**

In [ ]:

# Diccionario de meses
mapa_meses = {
    'F': 'Enero',
    'G': 'Febrero',
    'H': 'Marzo',
    'J': 'Abril',
    'K': 'Mayo',
    'M': 'Junio',
    'N': 'Julio',
    'Q': 'Agosto',
    'U': 'Septiembre',
    'V': 'Octubre',
    'X': 'Noviembre',
    'Z': 'Diciembre'
}
def transformar_dataset(df):
    # Asegurar que Nemo está como fecha
    df['Nemo'] = pd.to_datetime(df['Nemo'], dayfirst=True)

    # Formato largo
    df_long = df.melt(
        id_vars='Nemo',
        var_name='Contrato',
        value_name='Precio'
    )

    # Tipo = primeras 3 letras
    df_long['Tipo'] = df_long['Contrato'].str[:3]

    # Mes = letra 4 convertida
    df_long['Mes'] = df_long['Contrato'].str[3].map(mapa_meses)

    # Año = posiciones 5-6 convertidas a 20xx
    df_long['Año'] = df_long['Contrato'].str[4:6].astype(int).apply(lambda x: 2000 + x)

    # Fecha = Nemo original
    df_long['Fecha'] = df_long['Nemo']

    # Reordenar columnas
    df_final = df_long[['Contrato', 'Tipo', 'Mes', 'Año', 'Fecha', 'Precio']]

    return df_final

**DATASETS ORGANIZADOS**

In [50]:
MTBF = transformar_dataset(cierre_mtb)
NTBF = transformar_dataset(cierre_ntb)
DTBF = transformar_dataset(cierre_dtb)
ELMF = transformar_dataset(cierre_dtb)

MTBF= MTBF.rename(columns={
    'Contrato': 'Nemotecnico'
})

NTBF= NTBF.rename(columns={
    'Contrato': 'Nemotecnico'
})

DTBF= DTBF.rename(columns={
    'Contrato': 'Nemotecnico'
})
ELMF= ELMF.rename(columns={
    'Contrato': 'Nemotecnico'
})

**ACÁ SE ORGANIZAN NEGOCIACIONES ELECTRÓNICAS**

In [51]:
neg_electronica = neg_electronica.rename(columns={
    'MEJOR PRECIO DE COMPRA (BID)': 'BID',
    'CANTIDAD DE CONTRATOS CON EL MEJOR PRECIO DE COMPRA': 'CABID',
    'MEJOR PRECIO DE VENTA (OFFER)': 'OFFER',
    'CANTIDAD DE CONTRATOS CON EL MEJOR PRECIO DE VENTA': 'CAOFFER'
})

In [52]:
# Mapa de meses
mapa_meses = {
    'F': 'Enero',
    'G': 'Febrero',
    'H': 'Marzo',
    'J': 'Abril',
    'K': 'Mayo',
    'M': 'Junio',
    'N': 'Julio',
    'Q': 'Agosto',
    'U': 'Septiembre',
    'V': 'Octubre',
    'X': 'Noviembre',
    'Z': 'Diciembre'
}

def transformar_neg(df):
    # Asegurar que FECHA esté como datetime
    df['FECHA'] = pd.to_datetime(df['FECHA'], dayfirst=True)

    # Renombrar CONTRATO → Contrato para consistencia
    df = df.rename(columns={'CONTRATO': 'Contrato'})

    # Tipo = primeras 3 letras
    df['Tipo'] = df['Contrato'].str[:3]

    # Mes = 4ta letra convertida
    df['Mes'] = df['Contrato'].str[3].map(mapa_meses)

    # Año = posiciones 5-6 → 20xx
    df['Año'] = df['Contrato'].str[4:6].astype(int).apply(lambda x: 2000 + x)

    return df

In [53]:
NEGEF= transformar_neg(neg_electronica)
NEGEF = NEGEF.rename(columns={
    'Contrato':'Nemotecnico'
})
NEGEF = NEGEF[~NEGEF['Nemotecnico'].str.startswith('ELB')]
#ORGANIZAR ORDEN

# Columnas nuevas
nuevas = ['Tipo', 'Mes', 'Año']

# Lista actual de columnas
cols = list(NEGEF.columns)

# Posición donde está la columna "Convocado"
idx = cols.index('Nemotecnico')

# Construir nuevo orden:
#   - todas las columnas antes de Convocado
#   - Convocado
#   - nuevas columnas
#   - el resto
nuevo_orden = (
    cols[:idx+1] +
    nuevas +
    [c for c in cols if c not in nuevas and c not in cols[:idx+1]]
)

# Reordenar dataframe
NEGEF = NEGEF[nuevo_orden]

NEGEF

           FECHA Nemotecnico Tipo         Mes   Año  BID CABID OFFER CAOFFER
0     2024-01-02     ELMM25F  ELM       Junio  2025    0     0   390       1
1     2024-01-02     ELMN25F  ELM       Julio  2025    0     0   393       1
2     2024-01-02     ELMQ25F  ELM      Agosto  2025    0     0   400       1
3     2024-01-02     ELMU25F  ELM  Septiembre  2025    0     0   400       1
7     2024-01-03     ELMM25F  ELM       Junio  2025    0     0   390       1
...          ...         ...  ...         ...   ...  ...   ...   ...     ...
10494 2025-11-12     ELMZ26F  ELM   Diciembre  2026  320    10     0       0
10495 2025-11-12     ELMM27F  ELM       Junio  2027    0     0   400      10
10496 2025-11-12     ELMN27F  ELM       Julio  2027    0     0   400      10
10497 2025-11-12     ELMQ27F  ELM      Agosto  2027    0     0   400      10
10498 2025-11-12     ELMU27F  ELM  Septiembre  2027    0     0   400       5

[8808 rows x 9 columns]

**ACÁ SE ORGANIZAN CONVOCATORIAS**

In [54]:
CONV.columns

Index(['Fecha Convocatoria', 'Nemotecnico', 'Contrato convocado',
       'Precio Adjudicado $/kWh', 'Cantidad de Energía Adjudicada GWh',
       'Cantidad de Energía Expuesta en Compra GWh',
       'Cantidad de Energía Expuesta en Venta GWh'],
      dtype='object')

In [55]:
CONV = CONV.rename(columns={
    'Fecha Convocatoria': 'Fecha',
    'Contrato convocado': 'Convocado',
    'Precio Adjudicado $/kWh': 'Precio Adjudicado',
    'Cantidad de Energía Adjudicada GWh': 'Energía Adjudicada',
    'Cantidad de Energía Expuesta en Compra GWh':'Expuesta Compra',
    'Cantidad de Energía Expuesta en Venta GWh':'Expuesta Venta'
})

In [56]:
CONV.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7190 entries, 0 to 7189
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Fecha               7190 non-null   datetime64[ns]
 1   Nemotecnico         7190 non-null   object
 2   Convocado           7190 non-null   object
 3   Precio Adjudicado   7190 non-null   object
 4   Energía Adjudicada  7190 non-null   object
 5   Expuesta Compra     7190 non-null   object
 6   Expuesta Venta      7190 non-null   object
dtypes: datetime64[ns](1), object(6)
memory usage: 393.3+ KB

In [57]:
CONV = CONV[~CONV['Nemotecnico'].str.startswith('ELB')]
CONV['Convocado'] = pd.to_datetime(CONV['Convocado'], dayfirst=True, errors='coerce')
# Mapa de letras a meses
mes_map = {
    'F': 'Enero',
    'G': 'Febrero',
    'H': 'Marzo',
    'J': 'Abril',
    'K': 'Mayo',
    'M': 'Junio',
    'N': 'Julio',
    'Q': 'Agosto',
    'U': 'Septiembre',
    'V': 'Octubre',
    'X': 'Noviembre',
    'Z': 'Diciembre'
}

# Extraer Tipo, Mes (letra) y Año (2 dígitos) desde el nemotécnico de la columna "Contrato"
CONV[['Tipo', 'MesLetra', 'Año2d']] = CONV['Nemotecnico'].str.extract(
    r'([A-Z]{3})([A-Z])(\d{2})'
)

# Convertir la letra del mes a número
CONV['Mes'] = CONV['MesLetra'].map(mes_map)

# Convertir año de 2 dígitos a formato completo
CONV['Año'] = CONV['Año2d'].astype(int) + 2000

# Eliminar temporales
CONV = CONV.drop(columns=['MesLetra', 'Año2d'])
##############################################################################################
#ORGANIZAR ORDEN
# Columnas nuevas
nuevas = ['Tipo', 'Mes', 'Año']

# Lista actual de columnas
cols = list(CONV.columns)

# Posición donde está la columna "Convocado"
idx = cols.index('Convocado')

# Construir nuevo orden:
#   - todas las columnas antes de Convocado
#   - Convocado
#   - nuevas columnas
#   - el resto
nuevo_orden = (
    cols[:idx+1] +
    nuevas +
    [c for c in cols if c not in nuevas and c not in cols[:idx+1]]
)

# Reordenar dataframe
CONV = CONV[nuevo_orden]

CONV

,Fecha,Nemotecnico,Convocado,Tipo,Mes,Año,Precio Adjudicado,Energía Adjudicada,Expuesta Compra,Expuesta Venta
0,2022-10-19,ELMV22F,2022-10-01,ELM,Octubre,2022,-,-,-,-
1,2022-10-19,ELMX22F,2022-11-01,ELM,Noviembre,2022,395,0.36,0.36,0.36
2,2022-10-19,ELMZ22F,2022-12-01,ELM,Diciembre,2022,-,-,0.36,0.72
5,2022-11-09,ELMX22F,2022-11-01,ELM,Noviembre,2022,-,-,-,-
6,2022-11-09,ELMZ22F,2022-12-01,ELM,Diciembre,2022,-,-,0.72,0.36
...,...,...,...,...,...,...,...,...,...,...
7185,2025-11-06,NTBM27F,2027-06-01,NTB,Junio,2027,-,-,-,-
7186,2025-11-06,NTBN27F,2027-07-01,NTB,Julio,2027,-,-,-,-
7187,2025-11-06,NTBQ27F,2027-08-01,NTB,Agosto,2027,-,-,-,-
7188,2025-11-06,NTBU27F,2027-09-01,NTB,Septiembre,2027,-,-,-,-
7189,2025-11-06,NTBV27F,2027-10-01,NTB,Octubre,2027,-,-,-,-

**ACÁ SE ORGANIZA ÚLTIMAS**

In [58]:
ultimas = ultimas.drop(columns=['Mes contrato'])
ultimas= ultimas.rename(columns={
    'Instrumento': 'Tipo'
})

KeyError: "['Mes contrato'] not found in axis"

In [59]:
ultimas.columns
ultimas= ultimas.rename(columns={
    'Carga total kWh': 'Carga Total',
    'Sesión de negociación': 'Sesión',
    'Contrato': 'Nemotecnico'
})

In [62]:
ultimas
# Diccionario de meses según Derivex
mes_map = {
    'F': 'Enero',
    'G': 'Febrero',
    'H': 'Marzo',
    'J': 'Abril',
    'K': 'Mayo',
    'M': 'Junio',
    'N': 'Julio',
    'Q': 'Agosto',
    'U': 'Septiembre',
    'V': 'Octubre',
    'X': 'Noviembre',
    'Z': 'Diciembre'
}

# --- Generar columnas a partir del nemotécnico (Contrato) ---

# Mes → se toma la 4ta letra del nemotécnico
ultimas['Mes'] = ultimas['Nemotecnico'].str[3].map(mes_map)

# Año → se toma la posición 5 y 6, y se convierte a 20XX
ultimas['Año'] = '20' + ultimas['Nemotecnico'].str[4:6]
ultimas['Año'] = ultimas['Año'].astype(int)

**Acá se organiza Resumen**

In [79]:
resumen

          Mes    kWh - mes  GWh - mes
0  2024-01-01  195120000.0     195.12
1  2024-02-01   71280000.0      71.28
2  2024-03-01   30600000.0      30.60
3  2024-04-01   23450000.0      23.45
4  2024-05-01   44810000.0      44.81
5  2024-06-01   36720000.0      36.72
6  2024-07-01    6480000.0       6.48
7  2024-08-01  119880000.0     119.88
8  2024-09-01   25920000.0      25.92
9  2024-10-01   10800000.0      10.80
10 2024-11-01   10080000.0      10.08
11 2024-12-01    7920000.0       7.92
13 2025-01-01    4830000.0       4.83
14 2025-02-01  132120000.0     132.12
15 2025-03-01   18720000.0      18.72
16 2025-04-01   61920000.0      61.92
17 2025-05-01   64080000.0      64.08
18 2025-06-01   51480000.0      51.48
19 2025-07-01   41030000.0      41.03
20 2025-08-01   58680000.0      58.68
21 2025-09-01   80430000.0      80.43
22 2025-10-01   69840000.0      69.84
23 2025-11-01   17280000.0      17.28
24 2025-12-01          NaN       0.00

In [127]:
#Eliminar total de tabla
resumen = resumen[~resumen['Mes'].astype(str).str.contains("Total", case=False, na=False)]
resumen['Mes'] = pd.to_datetime(resumen['Mes'], errors='coerce')

# Asegurar que Mes es fecha
resumen['Mes'] = pd.to_datetime(resumen['Mes'], errors='coerce')

# Crear columna Año
resumen['Año'] = resumen['Mes'].dt.year

# Crear columna con el nombre del mes
resumen['MesNombre'] = resumen['Mes'].dt.month_name(locale='es_ES')

#------------------------------------------------------------------------#
# Asegurar que Mes es fecha
resumen['Mes'] = pd.to_datetime(resumen['Mes'], errors='coerce')

# Crear columna Año
resumen['Año'] = resumen['Mes'].dt.year

# Crear columna con el nombre del mes
resumen['MesNombre'] = resumen['Mes'].dt.month_name(locale='es_ES')

C:\Users\Jhon Fernando Tascón\AppData\Local\Temp\ipykernel_18960\375082932.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resumen['Mes'] = pd.to_datetime(resumen['Mes'], errors='coerce')
C:\Users\Jhon Fernando Tascón\AppData\Local\Temp\ipykernel_18960\375082932.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resumen['Mes'] = pd.to_datetime(resumen['Mes'], errors='coerce')
C:\Users\Jhon Fernando Tascón\AppData\Local\Temp\ipykernel_18960\375082932.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resumen['Año'] = resumen['Mes'].dt.year
C:\Users\Jhon Fernando Tascón\AppData\Local\Temp\ipykernel_18960\375082932.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resumen['MesNombre'] = resumen['Mes'].dt.month_name(locale='es_ES')
C:\Users\Jhon Fernando Tascón\AppData\Local\Temp\ipykernel_18960\375082932.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resumen['Mes'] = pd.to_datetime(resumen['Mes'], errors='coerce')
C:\Users\Jhon Fernando Tascón\AppData\Local\Temp\ipykernel_18960\375082932.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resumen['Año'] = resumen['Mes'].dt.year
C:\Users\Jhon Fernando Tascón\AppData\Local\Temp\ipykernel_18960\375082932.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resumen['MesNombre'] = resumen['Mes'].dt.month_name(locale='es_ES')

In [128]:
resumen= resumen.rename(columns={
    'kWh - mes': 'kWh',
    'GWh - mes': 'GWh',
    'MesNombre': 'Mes'
})

In [129]:
resumen

          Mes          kWh     GWh   Año         Mes
0  2024-01-01  195120000.0  195.12  2024       Enero
1  2024-02-01   71280000.0   71.28  2024     Febrero
2  2024-03-01   30600000.0   30.60  2024       Marzo
3  2024-04-01   23450000.0   23.45  2024       Abril
4  2024-05-01   44810000.0   44.81  2024        Mayo
5  2024-06-01   36720000.0   36.72  2024       Junio
6  2024-07-01    6480000.0    6.48  2024       Julio
7  2024-08-01  119880000.0  119.88  2024      Agosto
8  2024-09-01   25920000.0   25.92  2024  Septiembre
9  2024-10-01   10800000.0   10.80  2024     Octubre
10 2024-11-01   10080000.0   10.08  2024   Noviembre
11 2024-12-01    7920000.0    7.92  2024   Diciembre
13 2025-01-01    4830000.0    4.83  2025       Enero
14 2025-02-01  132120000.0  132.12  2025     Febrero
15 2025-03-01   18720000.0   18.72  2025       Marzo
16 2025-04-01   61920000.0   61.92  2025       Abril
17 2025-05-01   64080000.0   64.08  2025        Mayo
18 2025-06-01   51480000.0   51.48  2025       Junio
19 2025-07-01   41030000.0   41.03  2025       Julio
20 2025-08-01   58680000.0   58.68  2025      Agosto
21 2025-09-01   80430000.0   80.43  2025  Septiembre
22 2025-10-01   69840000.0   69.84  2025     Octubre
23 2025-11-01   17280000.0   17.28  2025   Noviembre
24 2025-12-01          NaN    0.00  2025   Diciembre

**ACÁ SE ACOMODA PRECIOS DE REFERENCIA**

In [130]:
REFE
REFE= REFE.rename(columns={
    'Nemotécnico': 'Nemotecnico',
    'Precio $/kWh': 'Precio'
})
REFE = REFE.drop(columns=['Contrato'])

KeyError: "['Contrato'] not found in axis"

In [131]:
REFE
# Diccionario de meses según Derivex
mes_map = {
    'F': 'Enero',
    'G': 'Febrero',
    'H': 'Marzo',
    'J': 'Abril',
    'K': 'Mayo',
    'M': 'Junio',
    'N': 'Julio',
    'Q': 'Agosto',
    'U': 'Septiembre',
    'V': 'Octubre',
    'X': 'Noviembre',
    'Z': 'Diciembre'
}

# --- Generar columnas a partir del nemotécnico (Contrato) ---
# Año → se toma la posición 5 y 6, y se convierte a 20XX
REFE['Año'] = '20' + REFE['Nemotecnico'].str[4:6]
REFE['Año'] = REFE['Año'].astype(int)
# Mes → se toma la 4ta letra del nemotécnico
REFE['Mes'] =REFE['Nemotecnico'].str[3].map(mes_map)

**Después de todo se quedan con los siguientes conjuntos de Datos**
Histórico de Precios de los contratos

## Variables de los df ELMF-DTBF-MTBF-NTBF

| **Columna**    | **Descripción** |
|----------------|-----------------|
| **Nemotecnico** | Código único del contrato futuro de energía. Identifica el tipo de contrato, la fecha de vencimiento y características del instrumento (por ejemplo: `DTBF24F`). |
| **Tipo**        | Clasificación del contrato según el mercado o producto al que pertenece (por ejemplo: `DTB`). Permite diferenciar entre los distintos tipos de futuros negociados. |
| **Mes**         | Nombre del mes correspondiente al registro, extraído de la fecha del contrato (por ejemplo: `Enero`). |
| **Año**         | Año del registro, tomado de la fecha del contrato (por ejemplo: `2024`). |
| **Fecha**       | Fecha exacta en la que se registró el precio del contrato futuro, en formato `YYYY-MM-DD` (por ejemplo: `2024-01-02`). |
| **Precio**      | Precio del contrato futuro expresado normalmente en $/kWh. Representa el valor negociado en esa fecha para ese contrato. |

## Variables de NEGEF

| **Columna**       | **Descripción**                                                                                     |
|---------------|-------------------------------------------------------------------------------------------------|
| **FECHA**         | Fecha en la que se registra la información de mercado (formato YYYY-MM-DD).                     |
| **Nemotecnico**   | Código del contrato de futuros de energía de Derivex; incluye tipo de contrato, mes y año.      |
| **Tipo**          | Tipo de contrato (ELM, ELS, DTB, MTB, etc.), derivado del nemotécnico.                          |
| **Mes**           | Mes de entrega del contrato expresado en texto (Enero, Febrero, etc.).                          |
| **Año**           | Año de entrega del contrato; extraído del nemotécnico.                                          |
| **BID**           | Mejor precio de compra ofertado por los agentes para ese contrato en la fecha dada.             |
| **CABID**         | Cantidad de energía asociada a la oferta de compra (BID).                                       |
| **OFFER**         | Mejor precio de venta ofertado por los agentes para ese contrato en la fecha dada.              |
| **CAOFFER**       | Cantidad de energía asociada a la oferta de venta (OFFER).                                      |

## Variables de ultimas

| **Columna**                | **Descripción**                                                                                              |
|-------------------------|----------------------------------------------------------------------------------------------------------|
| **Fecha**                   | Fecha en la que se realizó la negociación del contrato (formato YYYY-MM-DD).                             |
| **Instrumento**             | Tipo de contrato negociado en Derivex (por ejemplo, ELM, ELS, DTB).                                      |
| **Contrato**                | Nemotécnico completo del contrato, que incluye tipo, mes y año de entrega.                              |
| **Mes contrato**            | Fecha correspondiente al mes y año de entrega del contrato (primer día del mes).                        |
| **Precio**                  | Precio al cual se negoció el contrato, expresado en $/kWh.                                               |
| **Cantidad**                | Cantidad de energía negociada en GWh o en bloques definidos por Derivex.                                 |
| **Monto**                   | Valor total monetario de la negociación (Precio × Cantidad).                                             |
| **Carga total kWh**         | Energía total asociada a la negociación, expresada en kWh.                                               |
| **Negociación en bloque**   | Indica si la operación fue realizada bajo modalidad de bloque (“SI” o “NO”).                             |
| **Sesión de negociación**   | Tipo de sesión en la que se realizó la operación (por ejemplo, “Convocatoria”, “Regular”, etc.).         |

## Variables de REFE
| **Columna**             | **Descripción**                                                                                         |
|---------------------|-----------------------------------------------------------------------------------------------------|
| **Fecha Convocatoria**  | Fecha en la que Derivex realizó la convocatoria para definir el precio de referencia del contrato.  |
| **Nemotecnico**         | Código del contrato de futuros de energía. Incluye tipo (ELM), mes y año de entrega (ej. ELMF24F).  |
| **Precio**              | Precio de referencia adjudicado en la convocatoria ($/kWh).                                         |
| **Mes**                 | Nombre del mes de entrega del contrato, extraído del nemotécnico.                                   |
| **Año**                 | Año de entrega del contrato, extraído del nemotécnico.                                              |

## Variables de CONV

| Columna                                   | Descripción                                                                              |
|-------------------------------------------|-------------------------------------------------------------------------------------------|
| Fecha Convocatoria                        | Fecha oficial en la que Derivex realizó la convocatoria del contrato futuro de energía.|
| Nemotecnico                               | Código del contrato convocado. Identifica tipo (ELM), mes y año del contrato (ej. ELMX22F).|
| Contrato convocado                        | Fecha de entrega del contrato futuro convocado (mes y año de cumplimiento del contrato).|
| Precio Adjudicado (/kWh)                 | Precio final adjudicado en la convocatoria (/kWh). Si aparece “-”, significa que no hubo|
| Cantidad de Energía Adjudicada GWh        | Energía efectivamente adjudicada en la convocatoria, en GWh.|
| Cantidad de Energía Expuesta en Compra GWh| Energía ofertada por compradores (demanda) durante la convocatoria, en GWh.|
| Cantidad de Energía Expuesta en Venta GWh | Energía ofertada por vendedores (oferta) durante la convocatoria, en GWh.|

### Variables de df resumen

Este dataset consolida la cantidad total de energía negociada en el mercado de futuros de energía, agrupada por mes y año. Cada fila representa el volumen total transado en un mes específico.

| Columna | Descripción |
|--------|-------------|
| **Mes** | Fecha en formato `YYYY-MM-01` que representa el mes de negociación. Esta fecha funciona como marcador temporal del mes consolidado. |
| **kWh** | Cantidad total de energía negociada durante el mes, expresada en kilovatios-hora (kWh). |
| **GWh** | Conversión del valor anterior a gigavatios-hora (GWh). Se obtiene dividiendo `kWh / 1,000,000`. |
| **Año** | Año correspondiente al período de negociación. Extraído directamente de la columna *Mes*. |
| **Mes (nombre)** | Nombre del mes (Enero, Febrero, Marzo…), generado para facilitar análisis y visualizaciones. |